// ============================================================
//  Premer Gaan - songs
//
//  This file is the single source of truth for the playlist.
//  file : uniquely-named audio in /songs (unique names also bust
//         any cached copies on hosting/CDN).
//  cover: local artwork in /covers, downloaded from the iTunes Store.
//         Delete the cover field to fall back to searching iTunes
//         by artist + title at runtime.
//
//  AUTO-GENERATED by tools/sync-playlist.mjs - drop an mp3 into
//  /songs and re-run the script (or push, if the GitHub Action is
//  enabled) to add it to the playlist.
// ============================================================

var SONGS = [
  { title: "Notun Premer Gaan", artist: "Debraj Bhattacharya & Surangana Bandyopadhyay", file: "songs/notun-premer-gaan.mp3", cover: "covers/notun-premer-gaan.jpg" },
  { title: "Amar Vin Deshi Tara", artist: "Chandrabindoo", file: "songs/amar-vin-deshi-tara.mp3", cover: "covers/amar-vin-deshi-tara.jpg" },
  { title: "Baynankhoka", artist: "Chandrabindoo", file: "songs/baynankhoka.mp3", cover: "covers/baynankhoka.jpg" },
  { title: "Bhalobasa Basi", artist: "Saikat Bandyopadhyay", file: "songs/bhalobasa-basi.mp3", cover: "covers/bhalobasa-basi.jpg" },
  { title: "Ei Raat Tomar Amar", artist: "Hemanta Mukherjee", file: "songs/ei-raat-tomar-amar.mp3", cover: "covers/ei-raat-tomar-amar.jpg" },
  { title: "Ek Minute Er Chumu", artist: "Debraj Bhattacharya", file: "songs/ek-minute-er-chumu.mp3", cover: "covers/ek-minute-er-chumu.jpg" },
  { title: "Ghum Ghum Ei Chokhe", artist: "Abir Biswas & Jeet Gannguli", file: "songs/ghum-ghum-ei-chokhe.mp3", cover: "covers/ghum-ghum-ei-chokhe.jpg" },
  { title: "It's Only Pyaar", artist: "Samidh Mukherjee, Rishi, Kunal Ganjawala & Monali Thakur", file: "songs/its-only-pyaar.mp3", cover: "covers/it-s-only-pyaar.jpg" },
  { title: "Jao Pakhi Antaheen", artist: "Shreya Ghoshal, Pranab Biswas, Aninda Chatterjee & Chandril Bhattacharya", file: "songs/jao-pakhi-antaheen.mp3", cover: "covers/jao-pakhi-antaheen.jpg" },
  { title: "Jeno Kichu Mone Koron", artist: "Akhil Bandhu Ghosh", file: "songs/jeno-kichu-mone-koron.mp3", cover: "covers/jeno-kichu-mone-koron.jpg" },
  { title: "Jodi Boli", artist: "Pratik Kundu & Sudeshna Das", file: "songs/jodi-boli.mp3", cover: "covers/jodi-boli.jpg" },
  { title: "Ke Tui Ey Bol", artist: "Arijit Singh", file: "songs/ke-tui-ey-bol.mp3", cover: "covers/ke-tui-ey-bol.jpg" },
  { title: "Keno Je Toke", artist: "Raj Barman", file: "songs/keno-je-toke.mp3", cover: "covers/keno-je-toke.jpg" },
  { title: "Kothin", artist: "Ash King & Sayani Ghosh", file: "songs/kothin.mp3", cover: "covers/kothin.jpg" },
  { title: "Mon Kharape", artist: "Sonu Nigam, Antara Mitra, Indraadip Dasgupta & Barish", file: "songs/mon-kharape.mp3", cover: "covers/mon-kharape.jpg" },
  { title: "Mon", artist: "Jeet Gannguli", file: "songs/mon.mp3", cover: "covers/mon.jpg" },
  { title: "Mone", artist: "Chandrabindoo", file: "songs/mone.mp3", cover: "covers/mone.jpg" },
  { title: "Muthor Romal", artist: "Antara Chowdhury, Srikanto Acharya, Aninda Chatterjee & Chandril Bhattacharya", file: "songs/muchar-romal.mp3", cover: "covers/muthor-romal.jpg" },
  { title: "Nesha Nesha", artist: "Sunidhi Chauhan & Anindya Chatterjee", file: "songs/nesha-nesha.mp3", cover: "covers/nesha-nesha.jpg" },
  { title: "O My Love", artist: "Kunal Ganjawala", file: "songs/o-my-love.mp3", cover: "covers/o-my-love.jpg" },
  { title: "Pather Prante Oi", artist: "Ranjan Prasad", file: "songs/pather-prante-oi.mp3", cover: "covers/pather-prante-oi.jpg" },
  { title: "Pran Dite Chai", artist: "Sabrina Bashir", file: "songs/pran-dite-chai.mp3", cover: "covers/pran-dite-chai.jpg" },
  { title: "Saajna Pass Ay Tu Jara", artist: "Shaan & Mahalakshmi Iyer", file: "songs/saajna-pass-ay-tu-jara.mp3", cover: "covers/saajna-pass-ay-tu-jara.jpg" },
  { title: "Se Je Boshe Ache", artist: "Arnob", file: "songs/se-je-boshe-ache.mp3", cover: "covers/se-je-boshe-ache.jpg" },
  { title: "Shedin Dekha Hoyechilo", artist: "Kunal Ganjawala", file: "songs/shedin-dekha-hoyechilo.mp3", cover: "covers/shedin-dekha-hoyechilo.jpg" },
  { title: "Tomake Chai", artist: "Arijit Singh", file: "songs/tomake-chai.mp3", cover: "covers/tomake-chai.jpg" },
  { title: "Tomar Kaner Dul", artist: "Suman Ghosh & Vinchigiri", file: "songs/tomar-kaner-dul.mp3", cover: "covers/tomar-kaner-dul.jpg" },
  { title: "Tomar Pichu Charbo Na", artist: "Nahid Hasan", file: "songs/tomar-pichu-charbo-na.mp3", cover: "covers/tomar-pichu-charbo-na.jpg" },
  { title: "Chokhe Chokhe", artist: "Shaan & Shreya Ghoshal", file: "songs/Chokhe Chokhe.mp3", cover: "covers/chokhe-chokhe.jpg" },
  { title: "Tomar Chokher Kalo", artist: "Rupam Islam", file: "songs/Tomar Chokher Kalo.mp3", cover: "covers/tomar-chokher-kalo.jpg" },
  { title: "Tomake Chai (Reprise)", artist: "", file: "songs/Tomake Chai (Reprise).mp3" },
];
